services:
  drift-cora-api:
    container_name: drift-cora-container
    build: .
    ports:
      - "9321:8001"
    environment:
      - OLLAMA_HOST=http://drift-ollama:11434
      - TRANSLATOR_API_URL=http://host.docker.internal:9322
    volumes:
      - .:/app
      - chroma_data:/app/chroma_db
    depends_on:
      - drift-ollama
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  drift-ollama:
    container_name: drift-ollama-container
    image: ollama/ollama:latest
    ports:
      - "9323:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  ollama_data:
  chroma_data:
